# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: showtime.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'showtime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshowtime.proto\x12\x08showtime\"(\n\x08Schedule\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"\x14\n\x04\x44\x61te\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"\x0f\n\rEmptySchedule2{\n\x08showtime\x12\x39\n\x08GetTimes\x12\x17.showtime.EmptySchedule\x1a\x12.showtime.Schedule0\x01\x12\x34\n\x0eGetMoviebyDate\x12\x0e.showtime.Date\x1a\x12.showtime.Scheduleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'showtime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCHEDULE']._serialized_start=28
  _globals['_SCHEDULE']._serialized_end=68
  _globals['_DATE']._serialized_start=70
  _globals['_DATE']._serialized_end=90
  _globals['_EMPTYSCHEDULE']._serialized_start=92
  _globals['_EMPTYSCHEDULE']._serialized_end=107
  _globals['_SHOWTIME']._serialized_start=109
  _globals['_SHOWTIME']._serialized_end=232
# @@protoc_insertion_point(module_scope)
